/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./docs/**/*.md",
    "./.vitepress/**/*.{vue,js,ts,jsx,tsx}",
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'archivo': ['Archivo', 'sans-serif'],
        'konkret': ['Konkret', 'sans-serif'],
        'headline': ['Konkret', 'sans-serif'],
        'body': ['Archivo', 'sans-serif'],
        'label': ['Konkret', 'sans-serif']
      },
      colors: {
        'dac-white': '#fcfce8',
        'dac-blue': '#28426D',
        'dac-orange': '#E25836',
        'dac-yellow': '#FFCC00',
        'dac-black': '#0F0F0F',
        'dac-violet': 'rgba(209, 196, 233, 1)',
        'dac-violet-dark': 'rgba(101, 31, 255, 1)',
        'dac-primary-dark': 'rgba(48, 48, 48, 1)',
        'dac-secondary': '#E25836',
        'dac-secondary-dark': '#28426D',
        "primary-fixed-dim": "#ffb4a2",
        "primary-fixed": "#ffdad2",
        "on-background": "#1b1d11",
        "on-primary-fixed": "#3c0700",
        "surface-dim": "#dbdbc8",
        "surface-variant": "#e3e4d0",
        "inverse-primary": "#ffb4a2",
        "secondary-fixed": "#d7e3ff",
        "surface": "#fbfbe7",
        "on-error": "#ffffff",
        "tertiary": "#5d5c5b",
        "tertiary-fixed": "#e5e2e1",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f2f2de",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#fcfce8",
        "on-secondary-fixed": "#001b3f",
        "on-tertiary-fixed": "#1c1b1b",
        "outline-variant": "#e1bfb7",
        "on-primary-container": "#fffbff",
        "surface-bright": "#fbfbe7",
        "surface-tint": "#ad3213",
        "on-primary-fixed-variant": "#8a1c00",
        "secondary-fixed-dim": "#aec7fa",
        "surface-container-low": "#f5f5e1",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e9e9d6",
        "on-surface": "#1b1d11",
        "error-container": "#ffdad6",
        "on-surface-variant": "#59413b",
        "inverse-surface": "#303124",
        "error": "#ba1a1a",
        "tertiary-container": "#767474",
        "secondary": "#28426d",
        "on-secondary-fixed-variant": "#2d4772",
        "on-primary": "#ffffff",
        "primary-container": "#cc4828",
        "surface-container": "#efefdb",
        "on-tertiary-fixed-variant": "#474646",
        "outline": "#8d716a",
        "tertiary-fixed-dim": "#c8c6c5",
        "secondary-container": "#b4ccff",
        "surface-container-highest": "#e3e4d0",
        "on-tertiary-container": "#f7feff",
        "primary": "#aa3011",
        "on-secondary-container": "#3d5682"
      }
    },
  },
  plugins: [require('@tailwindcss/typography')],
}